/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID,
    SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET,
    NEXT_PUBLIC_NOW_PLAYING_SPOTIFY_REFRESH_TOKEN: process.env.NEXT_PUBLIC_NOW_PLAYING_SPOTIFY_REFRESH_TOKEN,
    RECENTLY_PLAYED_SPOTIFY_REFRESH_TOKEN: process.env.NEXT_PUBLIC_RECENTLY_PLAYED_SPOTIFY_REFRESH_TOKEN,
    ON_REPEAT_SPOTIFY_REFRESH_TOKEN: process.env.ON_REPEAT_SPOTIFY_REFRESH_TOKEN,
    SPOTIFY_BASE64_STRING: process.env.SPOTIFY_BASE64_STRING,
  }
}

module.exports = nextConfig
